version: '3.9'
services:
  # frontend_imc:
  #   restart: always
  #   build: ./frontend
  #   ports:
  #     - 3000:3000
  #   platform: linux/x86_64
  #   working_dir: /app-frontend
  #   depends_on:
  #     backend_imc:
  #       condition: service_healthy
  #   # Os `healthcheck` devem garantir que a aplicação
  #   # está operacional, antes de liberar o container
  #   # healthcheck:
  #   #   test: ["CMD", "lsof", "-t", "-i:3000"]
  #   #   timeout: 10s
    #   retries: 5
  backend_imc:
    container_name: backend_imc
    build: ./backend
    ports:
      - 3001:3001
    platform: linux/x86_64
    working_dir: /app-backend
    depends_on:
      db_imc:
        condition: service_healthy
    environment:
      - APP_PORT=3001
      - JWT_SECRET=jwt_secret
      - DB_USER=root
      - DB_PASS=password
      - DB_HOST=db_imc
      - DB_PORT=3306
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
  db_imc:
    image: mysql:8.0.21
    container_name: db_imc
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
